### PR TITLE
Added pip cache directive to Travis configuration.

### PR DESCRIPTION
**Pull request by atombrella**
Added Python 3.6 to setup.py.

### CODE REVIEW

**Comment by atombrella** [comment]
Is the mismatch in license (Apache vs. GPL) in setup.py intentional?

**Comment by benjaoming** [comment]
> Is the mismatch in license (Apache vs. GPL) in setup.py intentional?

No, this is Apache, so says the LICENSE file, so I would go with that one :)

**Comment by benjaoming** [comment]
Thanks for noticing!

**Comment by benjaoming** [comment]
Thanks for noticing all this -- I don't know how you do this! ❤️

**Pull request merged**
