### PR TITLE
Fixed Django 1.9 {% load url from future %} compatibility issue

### PR DESCRIPTION
**Pull request by VCAMP**
- `notifymail.py` now checks the Django version the user is running
- If Django is > 1.9, `_send_user_notifications` renders a template without the deprecated {% load url from future %} tag.

### CODE REVIEW

**Comment by benjaoming** [comment]
You are very welcome to remove the `{% load url from future %}` entirely.. it's total legacy by now, and I don't think it should be supported.

**Comment by benjaoming** [comment]
And thanks for fixing :) Would you be able to implement the simpler fix?

**Comment by VCAMP** [comment]
Hi Ben,

You're welcome! Can do that now.

**Comment by benjaoming** [comment]
Awesome!

**Comment by VCAMP** [comment]
Should work fine now.

**Comment by benjaoming** [comment]
Looks good! Thanks so much for this!

**Pull request merged**
