### PR TITLE
Added Django 2 support

### PR DESCRIPTION
**Pull request by rsalmaso**
LINT fails because django 2.0 is python3 only

### CODE REVIEW

**Comment by rsalmaso** [comment]
@benjaoming related as https://github.com/django-wiki/django-wiki/pull/755 there could be a 1.0 release without django 2.0 support and start a new release with it (and at the same time drop python 2.7).

**Comment by benjaoming** [comment]
:+1: except for dropping Python 2.7 :)

...Still with the same reasoning as Django.. once 1.11 LTS can be dropped, we can drop Python 2.7

**Comment by benjaoming** [comment]
Let me just work a bit on the current master branch for a new release, and I'll let you know when to rebase!

Btw awesome work!!

**Comment by rsalmaso** [comment]
@benjaoming ok!

**Comment by rsalmaso** [comment]
@benjaoming it's ok
I'll wait for a cleaner PR

**Comment by benjaoming** [comment]
@rsalmaso other PRs have been merged and released in the 1.0 branch, we can continue to work on a 1.1 series with Django 2.0 support -- and if you need, you are welcome to toss aboard some of the older Django versions, together with Python 2.7 support.

**Comment by rsalmaso** [comment]
@benjaoming ok!

**Comment by benjaoming** [comment]
@rsalmaso thanks! :)

**Comment by rsalmaso** [comment]
Extract everything not really related to django 2. I'll update this PR when all others are merged.

**Comment by rsalmaso** [comment]
Ok, PR updated :smiley_cat:

**Comment by benjaoming** [comment]
Oh wow, sweet!!

**Pull request merged**
